services:
  api:
    container_name: onlineShopApi
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - mongo
      
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
  mongo-db: