services:
  api:
    # image: amineelgaini/online-shop-api
    build:
      context: .
      target: production
    ports:
      - "8000:8000"
    env_file:
      - .env
    
    environment:
      NODE_ENV: production
      MONGO_URI : "mongodb+srv://onlineShop:NSJzX27FEbcJbdG0@onlineshop.ewihd.mongodb.net/onlineShop?retryWrites=true&w=majority&appName=onlineShop" 
      PORT: 8000