services:
  api:
    build:
      context: .
      target: development
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://root:password@mongo:27017/myDatabase?authSource=admin
      PORT: 4000
    depends_on:
      - mongo

    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./package-lock.json
          action: rebuild
        
        - path: ./
          target: /app
          action: sync

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
      image: mongo-express
      restart: always
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example
        ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/myDatabase?authSource=admin
        ME_CONFIG_BASICAUTH: false
  
volumes:
  mongo-db: